server:
  port: 9080

spring:
  application:
    name: jackpot

  datasource:
    platform: mysql
    url: jdbc:mysql://testdb.cuxubggfoeux.ap-northeast-2.rds.amazonaws.com:3306/testDB
    username: admin
    password: Oriquack123!!
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전

  servlet:
    multipart:
      file-size-threshold: 1MB #spring.servlet.multipart.file-size-threshold: 파일이 메모리에 기록되는 임계값 (default: 0B)
      #      location: C:/Temp #spring.servlet.multipart.location: 업로드된 파일의 임시 저장 공간
      max-file-size: 100MB #spring.servlet.multipart.max-file-size: 파일의 최대 사이즈 (default: 1MB)
      max-request-size: 100MB #spring.servlet.multipart.max-request-size: 요청의 최대 사이즈 (default: 10MB)